blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

site_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='Skystore')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    slug = models.CharField(max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='содержимое')
    picture = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Превью')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=False, verbose_name='Статус')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}. Просмотрено {self.views_count} раз'

    class Meta:
        verbose_name = 'блоговая запись'
        verbose_name_plural = 'юлоговые записи'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'picture', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'body', 'picture', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="card-body">
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <p> Хотите удалить запись {{object.title}}? </p>>
        <button type="submit" class="btn btn-danger">Да</button>
        <a class="btn btn-secondary" href="{% url 'blog:list' %}">Нет</a>
    </form>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}

<div class="row text-center row-cols-1 row-cols-md-4 g-4">
    <div class="col">
        <div class="card h-100">
            <img class="card-img-top"
                 src="{{ object.picture | mymedia}}"
                 alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">({{object.slug}})</h6>
                <p class="card-text">{{object.body}}</p>
            </div>
            <div class="card-footer">
                <small class="text-body-secondary">Дата создания: {{object.created_at}}</small>
                <small class="text-body-secondary">Количество просмотров: {{object.views_count}}</small>
            </div>
            <div class="btn-group">
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:list' %}">Return</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:update' object.pk %}">Edit</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:delete' object.pk %}">Delete</a>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="card-body">
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
            {% if object %}
            Сохранить
            {% else %}
            Создать
            {% endif%}
        </button>
    </form>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content%}

<div class="row text-center row-cols-1 row-cols-md-4 g-4">
<div class="row text-left row-cols-1 row-cols-md-8 g-4">
    <nav class="ms-5">
        <a class="p-2 btn btn-primary" href="{% url 'blog:create' %}">Создать запись</a>
    </nav>
</div>

    {% for object in object_list %}
    <div class="col">
        <div class="card h-100">
            <img class="card-img-top"
                 src="{{ object.picture | mymedia}}"
                 alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">({{object.slug}})</h6>
                <p class="card-text">{{object.body}}</p>
            </div>
            <div class="card-footer">
                <small class="text-body-secondary">Дата создания: {{object.created_at}}</small>
                <small class="text-body-secondary">Количество просмотров: {{object.views_count}}</small>
            </div>
            <div class="btn-group">
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:view' object.pk %}">View</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:update' object.pk %}">Edit</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:delete' object.pk %}">Delete</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock %}