blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductDetailView, ProductListView, ContactsView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ModeratorProductUpdateView, CategoryListView, CategoryDeleteView, CategoryUpdateView, \
    CategoryCreateView, CategoryDetailView

app_name = 'Skystore'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view()),
    path('<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_page'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('<int:pk>/update_product', ProductUpdateView.as_view(), name='product_update'),
    path('<int:pk>/update_product/moderator', ModeratorProductUpdateView.as_view(), name='moderator_product_update'),
    path('<int:pk>/delete_product', ProductDeleteView.as_view(), name='product_delete'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('create_category/', CategoryCreateView.as_view(), name='create_category'),
    path('update_category/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category_page'),
    path('delete_category/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
]

site_shop/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home_page/', views.home),
    path('contacts/', views.contacts),
]

site_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='Skystore')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_password, verification_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/confirm/<str:token>', verification_view, name='register_confirm'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('genpassword/', generate_password, name='generate_password'),
]

catalog/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Название категории')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        CANCELED = 'CN', 'Canceled'

    title = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    picture = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                verbose_name='создатель')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT,
                              verbose_name='Статус публикации')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f'{self.title} - {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['-updated_at']
        permissions = [
            (
                'set_published',
                'Can publish product'
            ),
            (
                'change_description',
                'Can change description'
            ),
            (
                'change_category',
                'Can change category'
            )
        ]


class Version(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название версии')
    number = models.CharField(max_length=250, verbose_name='Номер версии')
    is_current = models.BooleanField(verbose_name='Признак текущей версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')

    def __str__(self):
        return f'{self.product} - {self.number} - {self.is_current}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

import re

from catalog.models import Product, Version, Category

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_current':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('creator', 'status')

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')

        if bool(re.search('|'.join(FORBIDDEN_WORDS), cleaned_data.lower())):
            raise forms.ValidationError('Были использованы запрещенные слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')

        if bool(re.search('|'.join(FORBIDDEN_WORDS), cleaned_data.lower())):
            raise forms.ValidationError('Были использованы запрещенные слова')

        return cleaned_data


class ModeratorProductForm(ProductForm):
    class Meta(ProductForm.Meta):
        exclude = ('title', 'creator', 'price', 'picture')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm, CategoryForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories_cache, get_products_cache


class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    permission_required = 'catalog.add_category'
    success_url = reverse_lazy('Skystore:category_list')


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        queryset = get_categories_cache()
        return queryset


class CategoryDetailView(DetailView):
    model = Category


class CategoryUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm

    permission_required = 'catalog.change_category'

    def get_success_url(self):
        return reverse('Skystore:category_update', args=[self.kwargs.get('pk')])


class CategoryDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Category
    permission_required = 'catalog.delete_category'
    success_url = reverse_lazy('Skystore:category_list')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('Skystore:product_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('Skystore:product_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        context_data['formset'] = VersionFormset()
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


class ModeratorProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ModeratorProductForm
    permission_required = ('catalog.set_published', 'catalog.change_description', 'catalog.change_category')

    def get_success_url(self):
        return reverse('Skystore:moderator_product_update', args=[self.kwargs.get('pk')])


class ProductListView(ListView):
    model = Product
    extra_context = {'title': 'Skystore'}

    def get_queryset(self):
        queryset = get_products_cache()
        if self.request.user.groups.filter(name='Moderators').exists():
            return queryset
        return queryset.filter(status='PB')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data.get('object_list'):
            product.version = product.version_set.filter(is_current=True).first()
        return context_data


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('Skystore:product_list')


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

catalog/templates/catalog/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <a  href="{% url 'Skystore:category_list' %}">Категории</a>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'Skystore:product_list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-primary" href="{% url 'users:logout' %}">Выйти</a>

        {% else %}
        <a class="p-2 btn btn-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-success" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

    </nav>
    {% if user.is_authenticated %}
    <div class="col-6"></div>
    <p class="text-primary" style="width: 10rem;" >{{user.email}}</p>
    {% endif %}

    </div>

catalog/templates/catalog/includes/inc_product.html
{% load my_tags %}
<div class="col-3 h-100">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4><a href="{% url 'Skystore:product_page' object.pk %}"
                   class="my-0 font-weight-normal">{{object.title}} </a></h4>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{object.version.number}}</h6>
            <h6 class="card-subtitle mb-2 text-body-secondary">({{object.category}})</h6>
        </div>
        <div class="ratio" style="--bs-aspect-ratio: 50%;">
            <img class="card-img-top"
                 src="{{ object.picture | mymedia}}"
                 alt="Card image cap">
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
            <p class="card-text"> {{ object.description|truncatechars:100 }} </p>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary"> Купить</button>

        </div>
        <div class="card-footer">
            <small class="text-body-secondary">Created at {{object.created_at}}}</small>
        </div>
        <div class="card-footer">
            <small class="text-body-secondary">Last updated {{object.updated_at}}}</small>
        </div>
        <div class="card-footer">
            <small class="text-body-secondary">Автор {{object.creator|default:'Не указан'}}</small>
        </div>
    </div>
</div>