blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductDetailView, ProductListView, ContactsView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ModeratorProductUpdateView, CategoryListView, CategoryDeleteView, CategoryUpdateView, \
    CategoryCreateView, CategoryDetailView

app_name = 'Skystore'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view()),
    path('<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_page'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('<int:pk>/update_product', ProductUpdateView.as_view(), name='product_update'),
    path('<int:pk>/update_product/moderator', ModeratorProductUpdateView.as_view(), name='moderator_product_update'),
    path('<int:pk>/delete_product', ProductDeleteView.as_view(), name='product_delete'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('create_category/', CategoryCreateView.as_view(), name='create_category'),
    path('update_category/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category_page'),
    path('delete_category/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
]

site_shop/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home_page/', views.home),
    path('contacts/', views.contacts),
]

site_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='Skystore')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Название категории')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        CANCELED = 'CN', 'Canceled'

    title = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    picture = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                verbose_name='создатель')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT,
                              verbose_name='Статус публикации')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f'{self.title} - {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['-updated_at']
        permissions = [
            (
                'set_published',
                'Can publish product'
            ),
            (
                'change_description',
                'Can change description'
            ),
            (
                'change_category',
                'Can change category'
            )
        ]


class Version(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название версии')
    number = models.CharField(max_length=250, verbose_name='Номер версии')
    is_current = models.BooleanField(verbose_name='Признак текущей версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')

    def __str__(self):
        return f'{self.product} - {self.number} - {self.is_current}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

import re

from catalog.models import Product, Version, Category

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_current':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('creator', 'status')

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')

        if bool(re.search('|'.join(FORBIDDEN_WORDS), cleaned_data.lower())):
            raise forms.ValidationError('Были использованы запрещенные слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')

        if bool(re.search('|'.join(FORBIDDEN_WORDS), cleaned_data.lower())):
            raise forms.ValidationError('Были использованы запрещенные слова')

        return cleaned_data


class ModeratorProductForm(ProductForm):
    class Meta(ProductForm.Meta):
        exclude = ('title', 'creator', 'price', 'picture')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm, CategoryForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories_cache, get_products_cache


class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    permission_required = 'catalog.add_category'
    success_url = reverse_lazy('Skystore:category_list')


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        queryset = get_categories_cache()
        return queryset


class CategoryDetailView(DetailView):
    model = Category


class CategoryUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm

    permission_required = 'catalog.change_category'

    def get_success_url(self):
        return reverse('Skystore:category_update', args=[self.kwargs.get('pk')])


class CategoryDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Category
    permission_required = 'catalog.delete_category'
    success_url = reverse_lazy('Skystore:category_list')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('Skystore:product_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('Skystore:product_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        context_data['formset'] = VersionFormset()
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


class ModeratorProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ModeratorProductForm
    permission_required = ('catalog.set_published', 'catalog.change_description', 'catalog.change_category')

    def get_success_url(self):
        return reverse('Skystore:moderator_product_update', args=[self.kwargs.get('pk')])


class ProductListView(ListView):
    model = Product
    extra_context = {'title': 'Skystore'}

    def get_queryset(self):
        queryset = get_products_cache()
        if self.request.user.groups.filter(name='Moderators').exists():
            return queryset
        return queryset.filter(status='PB')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data.get('object_list'):
            product.version = product.version_set.filter(is_current=True).first()
        return context_data


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('Skystore:product_list')


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="card-body">
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <p> Хотите удалить категорию {{object.title}}? </p>>
        <button type="submit" class="btn btn-danger">Да</button>
        <a class="btn btn-secondary" href="{% url 'Skystore:category_list' %}">Нет</a>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="col-3 h-100">
    <div class="btn-group mb-4" role="group" aria-label="Basic example">
        {% if perms.catalog.change_category %}
        <a class="btn btn-outline-primary" href="{% url 'Skystore:category_update' category.pk %}"
           role="button">Изменить
            категорию</a>
        {% endif %}
        {% if perms.catalog.delete_category %}
        <a class="btn btn-outline-danger" href="{% url 'Skystore:category_delete' category.pk %}" role="button">Удалить
            категорию</a>
        {% endif %}
        <a class="btn btn-outline-secondary" href="{% url 'Skystore:category_list'%}" role="button">Вернуться к
            списку категорий</a>
    </div>
</div>

<div class="row text-center row-cols-1 row-cols-md-4 g-4">
    <div class="col-3 h-100">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4><a href="{% url 'Skystore:category_page' object.pk %}"
                       class="my-0 font-weight-normal">{{object.category_name}} </a></h4>
            </div>
            <div class="card-body">
                {% if object.description %}
                <p class="card-text"> {{ object.description|truncatechars:100 }} </p>
                {% else %}
                <p class="card-text"> У категории отсутствует описание </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block content%}
<form method="post" enctype="multipart/form-data" action="" class="form-floating">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header text-center text-bg-info p-3">
                    {% if object %}
                    <h5 class="card-title">Редактирование категории {{ object.title }}</h5>
                    {% else %}
                    <h5 class="card-title">Добавление категории</h5>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-outline-secondary" href="{% url 'Skystore:category_list'%}" role="button">Вернуться к
            списку категорий</a>

                </div>
            </div>
        </div>
</form>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="col-12 mb-5" >
    {% if perms.catalog.add_category %}
    <a class="btn btn-outline-primary" href="{% url 'Skystore:create_category' %}" role="button">Создать категорию</a>
    {% endif %}
</div>

<ul class="list-group">
  {% for object in object_list %}
  <li><a href="{% url 'Skystore:category_page' object.pk  %}">{{object.category_name}}</a></li>
  {% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row text-center row-cols-1 row-cols-md-4 g-4">
        {% for object in object_list %}
        {% include 'catalog/includes/inc_product.html' %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="card-body">
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <p> Хотите удалить продукт {{object.title}}? </p>>
        <button type="submit" class="btn btn-danger">Да</button>
        <a class="btn btn-secondary" href="{% url 'Skystore:product_list' %}">Нет</a>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="col-3 h-100">
    <div class="btn-group mb-4" role="group" aria-label="Basic example">
        {% if user == object.creator %}
        <a class="btn btn-outline-primary" href="{% url 'Skystore:product_update' product.pk %}" role="button">Изменить
            продукт</a>
        {% elif perms.catalog.set_published and perms.catalog.change_description and perms.catalog.change_category %}
        <a class="btn btn-outline-primary" href="{% url 'Skystore:moderator_product_update' product.pk %}"
           role="button">Изменить
            продукт</a>
        {% endif %}
        {% if perms.catalog.delete_product %}
        <a class="btn btn-outline-danger" href="{% url 'Skystore:product_delete' product.pk %}" role="button">Удалить
            продукт</a>
        {% endif %}
        <a class="btn btn-outline-secondary" href="{% url 'Skystore:product_list'%}" role="button">Вернуться к
            списку</a>
    </div>
</div>

<div class="row text-center row-cols-1 row-cols-md-4 g-4">
    {% include 'catalog/includes/inc_product.html' %}
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content%}
<form method="post" enctype="multipart/form-data" action="" class="form-floating">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header text-center text-bg-info p-3">
                    {% if object %}
                    <h5 class="card-title">Редактирование продукта {{ object.title }}</h5>
                    {% else %}
                    <h5 class="card-title">Добавление продукта</h5>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>

                </div>
            </div>
        </div>

        {% if object %}
        {% if perms.catalog.change_version or user == object.creator %}

        <div class="col-6">
            <div class="card">
                <div class="card-header text-center text-bg-info p-3">
                    <h5 class="card-title">Версии продукта</h5>
                </div>
                <div class="card-body">
                    {{formset.management_form}}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="col-12 mb-5" >
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'Skystore:create_product' %}" role="button">Создать продукт</a>
    {% endif %}
</div>

<div class="row text-center row-cols-1 row-cols-md-4 g-4">
    {% for object in object_list %}
    {% include 'catalog/includes/inc_product.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_page.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row text-center row-cols-1 row-cols-md-4 g-4">
        {% include 'catalog/includes/inc_product.html' %}
    </div>
{% endblock %}